[project]
name = "sonfolio-shared"
version = "0.1.0"
description = "Shared utilities for Sonfolio (e.g., LilyPond helpers)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "python-ly>=0.9.9",
]

[build-system]
requires = ["hatchling>=1.18"]
build-backend = "hatchling.build"

